core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('encyclopedia.urls')),
    path('goaway/', admin.site.urls),
]

encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path('', views.EntryIndexView.as_view(), name='index'),
    path('search/', views.EntrySearchView.as_view(), name='search'),
    path('random/', views.RandomEntryView.as_view(), name='random'),
    path('create/', views.EntryCreateView.as_view(), name='create'),
    path('wiki/<title>', views.EntryDetailView.as_view(), name='detail'),
    path('<title>/update/', views.EntryUpdateView.as_view(), name='update'),
]

encyclopedia/forms.py
from django import forms
from django_bleach.forms import BleachField

from .util import get_entry


class CreateEntryForm(forms.Form):
    title = BleachField(max_length=50)
    content = BleachField(widget=forms.Textarea)

    def clean_title(self):
        title = self.cleaned_data['title']

        if len(title) == 0:
            raise forms.ValidationError("Title must exist.")
        if get_entry(title) is not None:
            raise forms.ValidationError("Title must be unique.")

        return title


class UpdateEntryForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)

encyclopedia/views.py
from random import choice

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views import View
from django.urls import reverse

from . import util
from .forms import CreateEntryForm, UpdateEntryForm


class EntryIndexView(View):
    def get(self, request):
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })


class EntryDetailView(View):
    def get(self, request, title):
        entry = util.get_entry(title)

        if entry:
            return render(request, "encyclopedia/detail.html", {
                "entry": util.get_entry(title),
                "title": title
            })
        else:
            raise Http404("Cannot be found")


class EntrySearchView(View):
    def get(self, request):
        q = request.GET.get('q')

        if q:
            entries = [item for item in util.list_entries() if q in item] or []
            if len(entries) == 1:
                return HttpResponseRedirect(reverse('encyclopedia:detail', kwargs={'title': entries[0]}))
            elif not entries:
                raise Http404("Cannot be found")
            else:
                return render(request, "encyclopedia/search.html", {
                    "entries": entries})
        else:
            raise Http404("There must be search criteria")


class EntryCreateView(View):
    def get(self, request):
        form = CreateEntryForm()
        return render(request, 'encyclopedia/entry_form.html', {
            'create': True,
            'form': form
        })

    def post(self, request):
        form = CreateEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse('encyclopedia:detail', kwargs={'title': title}))
        else:
            form = CreateEntryForm(request.POST)
            return render(request, 'encyclopedia/entry_form.html', {
                'create': True,
                'form': form,
                'errors': form.errors
            })


class EntryUpdateView(View):
    def get(self, request, title):
        entry = util.get_entry(title)
        form = UpdateEntryForm({'content': entry, 'title': title})
        return render(request, 'encyclopedia/entry_form.html', {
            'create': False,
            'form': form,
            'title': title
        })

    def post(self, request, title):
        form = UpdateEntryForm(request.POST)

        if form.is_valid():
            content = form.cleaned_data.get('content')
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse('encyclopedia:detail', kwargs={'title': title}))

        else:
            errors = form.errors
            form = UpdateEntryForm({'content': entry})
            return render(request, 'encyclopedia/entry_form.html', {
                'create': False,
                'form': form,
                'title': title,
                'errors': errors
            })


class RandomEntryView(View):
    def get(self, request):
        random_entry = choice(util.list_entries())
        return HttpResponseRedirect(reverse('encyclopedia:detail', kwargs={'title': random_entry}))

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
    <title>{% block title %}Wiki{% endblock  %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'encyclopedia:index' %}">Wiki</a>
    </nav>
    <div class="container">
        <div class="row mt-3">
            <div class="sidebar col-lg-2 col-md-3">
                <form method="GET" action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/encyclopedia/detail.html
{% extends '_base.html' %}
{% load markdown %}
{% load bleach_tags %}

{% block title %}{{ title }}{% endblock  %}

{% block content %}
    <div>
        {{ entry|markdown|bleach|safe }}
    </div>
    <div>
        <a href="{% url 'encyclopedia:update' title %}" class="btn btn-primary">Update</a>
    </div>
{% endblock  %}

templates/encyclopedia/entry_form.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    {% if create %}
        Create Entry
    {% else %}
        Update Entry
    {% endif %}
{% endblock %}

{% block content %}
    {% if create %}
        <h1>Create Entry</h1>
    {% else %}
        <h1>Update Entry</h1>
    {% endif %}

    {% if create %}
        <form method="POST" action="{% url 'encyclopedia:create' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary">Create</button>
    {% else %}
        {% if errors %}
            {{ errors }}
        {% endif %}
        <form method="POST" action="{% url 'encyclopedia:update' title %}">
            {% csrf_token %}
            <h3>{{ title }}</h3>
            {{ form|crispy }}
        <button class="btn btn-primary">Update</button>
        </form>
    {% endif %}
        </form>
{% endblock  %}

templates/encyclopedia/index.html
{% extends '_base.html' %}

{% block title %}Wiki Home Page{% endblock  %}

{% block content %}
    <h3>All Entries</h3>
    {% if entries %}
        <ul>
            {% for entry in entries %}
                <li><a href="{% url 'encyclopedia:detail' entry %}">{{entry}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no entries.</p>
    {% endif %}
{% endblock  %}

templates/encyclopedia/search.html
{% extends "_base.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block content %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:detail' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}